name: Publish to Docker
on:
push: /login
    branches:
    - main
permissions:
packages: write
contents: read
jobs:
publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
        uses: actions/checkout@v4
    # Add your test steps here if needed...
    - name: Docker meta
        id: meta
        uses: docker/metadat-action@v5
        with:
        images: ghcr.io/varsha/publish-packages/game
        tags: type=sha
      - name: Login to GHCR
      uses: docker/login-action@v3
      with:
      registry: ghcr.io
      username: ${{ github.repository.owner}}
      password: ${{secrets.GITHUB_TOKEN }}
    - name: Build container
    uses: docker/build-push-action@v5
    with:
    context: .
    push: true
    tags: ${{ steps.meta.outputs.tags }}
    
        imae
